#!/bin/bash

log_invocation() {
    echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" "$0" "$@"
}

cleanup_it87_payload() {
    rm -rf /lib/modules/*/updates/dkms/it87
    modprobe -r -v it87
    depmod
    echo "modprobe -D"
    modprobe -D it87
}