#!/bin/bash

if [[ "$1" != "status" ]];then
    echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" $0 $*
fi

PACKAGE_BASE=${TRIM_APPDEST}

supportKernelList=( "6.12.18-trim" "6.18.6-trim" "6.18.18-trim")

nowKernelVer=$(uname -r)
nowKernelBuildNum=$(uname -v | grep -oP '(?<=#)\d+')

case $1 in
start)
    uname -a
    echo "kernel_inf ${nowKernelVer} ${nowKernelBuildNum}"

    if [[ " ${supportKernelList[@]} " =~ " ${nowKernelVer} " ]]; then
        echo "${nowKernelVer} in supportKernelList"
    else
        echo "${nowKernelVer} not in supportKernelList"
        echo "Supported versions: ${supportKernelList[*]}"
        exit 1
    fi

    case "$nowKernelVer" in

        6.12.18-trim)
            echo "debug 6.12.18-trim"
            mkdir -p /lib/modules/6.12.18-trim/updates/dkms/it87
            cp -rf ${PACKAGE_BASE}/app/ite-it87_6.12.18-trim_3/* /lib/modules/6.12.18-trim/updates/dkms/it87/
            ;;

        6.18.6-trim)
            echo "debug 6.18.6-trim"
            mkdir -p /lib/modules/6.18.6-trim/updates/dkms/it87
            cp -rf ${PACKAGE_BASE}/app/ite-it87_6.18.6-trim-297-amd64/* /lib/modules/6.18.6-trim/updates/dkms/it87/
            ;;

        6.18.18-trim)
            echo "debug 6.18.18-trim"
            mkdir -p /lib/modules/6.18.18-trim/updates/dkms/it87
            if [[ ! "$nowKernelBuildNum" =~ ^[0-9]+$ ]]; then
                echo "Unsupported build number for ${nowKernelVer}: ${nowKernelBuildNum}"
                exit 1
            fi

            if (( nowKernelBuildNum < 570 )); then
                cp -rf ${PACKAGE_BASE}/app/ite-it87_6.18.18-trim-427-amd64/* /lib/modules/6.18.18-trim/updates/dkms/it87/
            else
                cp -rf ${PACKAGE_BASE}/app/ite-it87_6.18.18-trim-570-amd64/* /lib/modules/6.18.18-trim/updates/dkms/it87/
            fi
            ;;
        *)
    esac

    modprobe -r -v it87 || echo "unload it87 failed"
    depmod
    modprobe -v it87 || echo "load it87 failed"

    ;;
stop)
  modprobe -r -v it87 || echo "unload it87 failed"

    ;;
status)
    modlist=`lsmod |grep it87 | wc -l`
    if [[ -d "/lib/modules/$(uname -r)/updates/dkms/it87" && ! $modlist -eq 0 ]]; then
      exit 0
    else
      echo -e "$(date +'%Y/%m/%d %H:%M:%S')\t" $0 $*
      exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
